---
- name: List last 5 jobs in AAP
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    controller_host: "https://51.20.108.56"
    controller_username: "admin"
    controller_password: "chanukya123"
    validate_certs: false

  tasks:
    - name: Get job list from AAP
      ansible.controller.job_list:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ validate_certs }}"
      register: jobs

    - name: Show last 5 job summaries with URLs
      ansible.builtin.debug:
        msg: "Job ID={{ item.id }} | Name='{{ item.name | default('N/A') }}' | Status={{ item.status | default('N/A') }} | URL={{ controller_host }}{{ item.url }}"
      loop: "{{ (jobs.results | default(jobs.json.results | default([]))) 
                | sort(attribute='id') 
                | reverse 
                | list
                | slice(0,5) | first | default([]) }}"
      when: jobs.results | default(jobs.json.results | default([])) | length > 0

    - name: No jobs found message
      ansible.builtin.debug:
        msg: "No jobs found in AAP Controller!"
      when: jobs.results | default(jobs.json.results | default([])) | length == 0











      

 


