---
- name: Demo: List jobs in AAP
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    controller_host: "https://51.20.108.56"   # your AAP URL
    controller_username: "admin"              # your AAP admin user
    controller_password: "chanukya123"        # your AAP password
    validate_certs: false                     # false if self-signed cert
  tasks:
    - name: Get job list from AAP
      ansible.controller.job_list:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ validate_certs }}"
      register: jobs

    - name: Show raw response (proof of API call)
      ansible.builtin.debug:
        var: jobs

    - name: Show concise job summary
      ansible.builtin.debug:
        msg: "{{ item.id }} | {{ item.name }} | {{ item.status }}"
      loop: "{{ jobs.results | default(jobs.json.results | default([])) }}"

      

 


