---
- name: List Last 5 Jobs in AAP
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    controller_host: "https://51.20.108.56"
    controller_username: "admin"
    controller_password: "chanukya123"
    validate_certs: false

  tasks:
    - name: Get all jobs from controller
      ansible.controller.job_list:
      register: jobs

    - name: Display total jobs found
      debug:
        msg: "Total jobs found: {{ jobs.results | length }}"

    - name: Show last 5 job summaries
      debug:
        msg: "Job ID={{ item.id }} | Name='{{ item.name | default('N/A') }}' | Status={{ item.status | default('N/A') }}"
      loop: "{{ jobs.results | sort(attribute='id') | reverse | slice(0,5) }}"






      

 


