---
- name: Test AH namespace
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create a namespace in Automation Hub
      infra.ah_configuration.ah_namespace:
        name: demo_namespace
        state: present

