---
- name: List Last 5 Jobs in AAP (UI-friendly)
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    tower_host: "https://51.20.108.56"
    tower_username: "admin"
    tower_password: "chanukya123"
    validate_certs: false

  tasks:
    - name: Get all jobs from controller
      ansible.controller.job_list:
      register: jobs

    - name: Display total jobs found
      debug:
        msg: "Total jobs found: {{ jobs.results | length }}"

    - name: Show last 5 job summaries
      debug:
        msg: "Job ID={{ item.id }} | Name='{{ item.name | default('N/A') }}' | Status={{ item.status | default('N/A') }} | URL={{ tower_host }}{{ item.url }}"
      loop: "{{ jobs.results | sort(attribute='id') | reverse | slice(0,5) }}"







      

 


