---
- name: "Demo: List jobs in AAP"
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller
  vars:
    controller_host: "https://51.20.108.56"
    controller_username: "admin"
    controller_password: "chanukya123"
    validate_certs: false
  tasks:
    - name: Get job list from AAP
      ansible.controller.job_list:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ validate_certs }}"
      register: jobs

    - name: Show raw response (proof)
      ansible.builtin.debug:
        var: jobs

    - name: Show concise job summary
      ansible.builtin.debug:
        msg: "{{ item.id }} | {{ item.name }} | {{ item.status }}"
      loop: "{{ jobs.results | default(jobs.json.results | default([])) }}"








      

 


